CREATE TABLE trPanduan(
	[IdPanduan] INT PRIMARY KEY IDENTITY(1,1),
	[NamaPanduan] VARCHAR(MAX) NOT NULL,
	[DeskripsiPanduan] VARCHAR(MAX) NOT NULL,
	[IdUser] INT NOT NULL,
	FOREIGN KEY (IdUser) REFERENCES msUser(IdUser)
)